### PR TITLE
docker: use alpine instead of debian

### PR DESCRIPTION
**Pull request by tanguysegarra**
The run base image was debian:stable which was about 124MB...
With this change, the jinko image is now 38.3MB!
Litteraly unbeatable!

### CODE REVIEW

**Comment by tanguysegarra** [comment]
@BastienGermond would you like to approve this?

**Comment by tanguysegarra** [comment]
We managed to make the image even lighter: 9.54MB! New record to beat!

**Comment by BastienGermond** [comment]
Amazing work @tanguysegarra :tada: Good job :+1:

**Comment by tanguysegarra** [comment]
Well well well, the image is now 1.67MB!

**Review by CohenArthur — APPROVED** [review]

**Pull request merged**
